/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.addressbook;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author admin
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    String pkName=null;
    String pkMob=null;
   
    public MainPage() {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@172.16.7.208:1521:orcl","sheeba","java");
            st=con.createStatement();
        }
        catch(Exception e){ 
            System.out.println("Connection Error: "+e); 
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        click = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        findPanel = new javax.swing.JPanel();
        search = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        goBut = new javax.swing.JButton();
        addImgPanel = new javax.swing.JPanel();
        add = new javax.swing.JLabel();
        resultPane = new javax.swing.JScrollPane();
        ctList = new javax.swing.JTable(){
            public boolean isCellEditable(int row,int col){
                return false;
            }
        };
        addPanel = new javax.swing.JPanel();
        addHeading = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        mobLabel = new javax.swing.JLabel();
        mailLabel = new javax.swing.JLabel();
        ctName = new javax.swing.JTextField();
        ctMob = new javax.swing.JTextField();
        ctMail = new javax.swing.JTextField();
        addBt = new javax.swing.JButton();
        backImg1 = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        mobLabel1 = new javax.swing.JLabel();
        mailLabel1 = new javax.swing.JLabel();
        ctName1 = new javax.swing.JTextField();
        ctMob1 = new javax.swing.JTextField();
        ctMail1 = new javax.swing.JTextField();
        editImg = new javax.swing.JLabel();
        doneImg = new javax.swing.JLabel();
        delImg = new javax.swing.JLabel();
        backImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        click.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/click1.jpg"))); // NOI18N
        click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(click)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(click, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        getContentPane().add(homePanel, "card2");

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("Search");

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        goBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        goBut.setText("Go");
        goBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout findPanelLayout = new javax.swing.GroupLayout(findPanel);
        findPanel.setLayout(findPanelLayout);
        findPanelLayout.setHorizontalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(findPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goBut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        findPanelLayout.setVerticalGroup(
            findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, findPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(findPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/add.png"))); // NOI18N
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addImgPanelLayout = new javax.swing.GroupLayout(addImgPanel);
        addImgPanel.setLayout(addImgPanelLayout);
        addImgPanelLayout.setHorizontalGroup(
            addImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addImgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );
        addImgPanelLayout.setVerticalGroup(
            addImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addImgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        ctList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Mobile Number", "E-Mail"
            }
        ));
        ctList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctListMouseClicked(evt);
            }
        });
        resultPane.setViewportView(ctList);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(findPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addImgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(resultPane, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, "card3");

        addHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addHeading.setText("Add a New Contact");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLabel.setText("Name");

        mobLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobLabel.setText("Mobile Number");

        mailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mailLabel.setText("E-Mail");

        ctName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ctMob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ctMail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        addBt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBt.setText("ADD");
        addBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtActionPerformed(evt);
            }
        });

        backImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/back.png"))); // NOI18N
        backImg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backImg1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(addHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ctName)
                            .addComponent(ctMob)
                            .addComponent(ctMail, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(addBt))))
                .addContainerGap(197, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(backImg1)
                .addGap(64, 64, 64))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(addHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ctMob, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(mobLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctMail, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(addBt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backImg1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(addPanel, "card4");

        nameLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLabel1.setText("Name");

        mobLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobLabel1.setText("Mobile Number");

        mailLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mailLabel1.setText("E-Mail");

        ctName1.setEditable(false);
        ctName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ctMob1.setEditable(false);
        ctMob1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ctMail1.setEditable(false);
        ctMail1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        editImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/edit.png"))); // NOI18N
        editImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editImgMouseClicked(evt);
            }
        });

        doneImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/done1.png"))); // NOI18N
        doneImg.setToolTipText("");
        doneImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneImgMouseClicked(evt);
            }
        });

        delImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/delete.png"))); // NOI18N
        delImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delImgMouseClicked(evt);
            }
        });

        backImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/addressbook/back.png"))); // NOI18N
        backImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backImgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ctName1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(ctMob1)
                        .addComponent(ctMail1))
                    .addComponent(delImg))
                .addGap(72, 72, 72)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editImg)
                    .addComponent(doneImg, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ctName1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editImg))
                .addGap(37, 37, 37)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ctMob1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(mobLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(doneImg))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(editPanel, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        mainPanel.setVisible(true);
        loadContactList();
        addPanel.setVisible(false);
        editPanel.setVisible(false);
       
    }//GEN-LAST:event_clickMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        mainPanel.setVisible(false);
        addPanel.setVisible(true);
        editPanel.setVisible(false);
      
    }//GEN-LAST:event_addMouseClicked

    private void addBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtActionPerformed
        // TODO add your handling code here:
        String name = ctName.getText().trim();
        String mob = ctMob.getText();
        String mail = ctMail.getText();
        if(isNumeric(mob)){
          try{  
           String qry = "insert into addbook values('"+name+"','"+mob+"','"+mail+"')";
        
           int flag = st.executeUpdate(qry);
           if(flag>0){
            
               JOptionPane.showMessageDialog(this, "Contact Saved");
               homePanel.setVisible(false);
               addPanel.setVisible(false);
               mainPanel.setVisible(true);
               editPanel.setVisible(false);
               loadContactList();
               
           }
          }catch(Exception e){
              System.out.println("Insert Error: "+e);
          }
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Mobile Number");
        }
    }//GEN-LAST:event_addBtActionPerformed

    private void goButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButActionPerformed
        // TODO add your handling code here:
      String name = nameField.getText();
      loadContacts(name);
    }//GEN-LAST:event_goButActionPerformed

    private void ctListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctListMouseClicked
        // TODO add your handling code here:
        int index = ctList.getSelectedRow();
        TableModel model = ctList.getModel();
        String name = model.getValueAt(index, 0).toString();
        String mob = model.getValueAt(index, 1).toString();
        String mail = model.getValueAt(index, 2).toString();
        ctName1.setText(name);
        ctMob1.setText(mob);
        ctMail1.setText(mail);
        homePanel.setVisible(false);
        mainPanel.setVisible(false);
        addPanel.setVisible(false);
        editPanel.setVisible(true);
        
        
    }//GEN-LAST:event_ctListMouseClicked

    private void editImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editImgMouseClicked
        // TODO add your handling code here:
        pkName = ctName1.getText();
        pkMob = ctMob1.getText();
        ctName1.setEditable(true);
        ctMob1.setEditable(true);
        ctMail1.setEditable(true);
        editImg.setVisible(false);
        delImg.setVisible(false);
    }//GEN-LAST:event_editImgMouseClicked

    private void doneImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneImgMouseClicked
        // TODO add your handling code here:
        String newName = ctName1.getText();
        String newMob = ctMob1.getText();
        String newMail = ctMail1.getText();
        
        if(isNumeric(newMob)){
          try{  
           String qry = "update addbook set name='"+newName+"',mob='"+newMob+"',email='"
                +newMail+"' where name='"+pkName+"' and mob='"+pkMob+"'";
           int flag = st.executeUpdate(qry);
           if(flag>0){
            
               JOptionPane.showMessageDialog(this, "Contact Edited");
               homePanel.setVisible(false);
               addPanel.setVisible(false);
               mainPanel.setVisible(false);
               editPanel.setVisible(true);
               ctName1.setEditable(false);
               ctMob1.setEditable(false);
               ctMail1.setEditable(false);
               editImg.setVisible(true);
               delImg.setVisible(true);
               
               
           }
          }catch(Exception e){
              System.out.println("Update Error: "+e);
          }
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Mobile Number");
        }
    }//GEN-LAST:event_doneImgMouseClicked

    private void delImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delImgMouseClicked
        // TODO add your handling code here:
        String name = ctName1.getText().trim();
        String mob = ctMob1.getText();
        String mail = ctMail1.getText();
        
        if(isNumeric(mob)){
          try{  
           String qry = "delete from addbook where name='"+name+"' and mob='"
                   +mob+"'";
           int flag = st.executeUpdate(qry);
           if(flag>0){
            
               JOptionPane.showMessageDialog(this, "Contact deleted");
               homePanel.setVisible(false);
               addPanel.setVisible(false);
               mainPanel.setVisible(true);
               editPanel.setVisible(false);
               loadContactList();
               
           }
          }catch(Exception e){
              System.out.println("Delete Error: "+e);
          }
        }else{
            JOptionPane.showMessageDialog(this,"Invalid Mobile Number");
        }
    }//GEN-LAST:event_delImgMouseClicked

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        // TODO add your handling code here:
        String searchName = nameField.getText().trim();
        searchContact(searchName);
    }//GEN-LAST:event_nameFieldKeyTyped

    private void backImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backImgMouseClicked
        // TODO add your handling code here:
         homePanel.setVisible(false);
        mainPanel.setVisible(true);
        loadContactList();
        addPanel.setVisible(false);
        editPanel.setVisible(false);
    }//GEN-LAST:event_backImgMouseClicked

    private void backImg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backImg1MouseClicked
        // TODO add your handling code here:
         homePanel.setVisible(false);
        mainPanel.setVisible(true);
        loadContactList();
        addPanel.setVisible(false);
        editPanel.setVisible(false);
    }//GEN-LAST:event_backImg1MouseClicked
     public void searchContact(String pattern){
      String qry = "select * from addbook where name like '"+pattern+"%' order by name asc";
        try{
          rs = st.executeQuery(qry);
            DefaultTableModel dtm =(DefaultTableModel)ctList.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Object[] ob = {rs.getString("name").toString(),rs.getString("mob").toString(),rs.getString("email").toString()};
                dtm.addRow(ob);
            }
       
        }catch(Exception e){
          System.out.println("Load Contact: "+e);
        }
    }
    public void loadContactList(){
      String qry = "select * from addbook order by name asc";
        try{
          rs = st.executeQuery(qry);
            DefaultTableModel dtm =(DefaultTableModel)ctList.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Object[] ob = {rs.getString("name").toString(),rs.getString("mob").toString(),rs.getString("email").toString()};
                dtm.addRow(ob);
            }
       
        }catch(Exception e){
          System.out.println("Load Contact: "+e);
        }
    }
    public void loadContacts(String str){
         String qry = "select * from addbook where name = '"+str+"'";
        try{
          rs = st.executeQuery(qry);
            DefaultTableModel dtm =(DefaultTableModel)ctList.getModel();
            dtm.setRowCount(0);
            while(rs.next()){
                Object[] ob = {rs.getString("name").toString(),rs.getString("mob").toString(),rs.getString("email").toString()};
                dtm.addRow(ob);
            }
     
        }catch(Exception e){
        
        }
    }
    public boolean isNumeric(String str)
{
    for (char c : str.toCharArray())
    {
        if (!Character.isDigit(c)) return false;
    }
    return true;
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add;
    private javax.swing.JButton addBt;
    private javax.swing.JLabel addHeading;
    private javax.swing.JPanel addImgPanel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel backImg;
    private javax.swing.JLabel backImg1;
    private javax.swing.JLabel click;
    private javax.swing.JTable ctList;
    private javax.swing.JTextField ctMail;
    private javax.swing.JTextField ctMail1;
    private javax.swing.JTextField ctMob;
    private javax.swing.JTextField ctMob1;
    private javax.swing.JTextField ctName;
    private javax.swing.JTextField ctName1;
    private javax.swing.JLabel delImg;
    private javax.swing.JLabel doneImg;
    private javax.swing.JLabel editImg;
    private javax.swing.JPanel editPanel;
    private javax.swing.JPanel findPanel;
    private javax.swing.JButton goBut;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JLabel mailLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mobLabel;
    private javax.swing.JLabel mobLabel1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JScrollPane resultPane;
    private javax.swing.JLabel search;
    // End of variables declaration//GEN-END:variables
}
